spring:
  profiles:
    active: dev
---
server:
  port: 80
spring:
  profiles: dev
  application:
    name: springcloud-dev
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka/

---
server:
  port: 81
spring:
  profiles: test
  application:
    name: springcloud-test
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka/